#! -*- coding: utf-8 -*-

# author: forcemain@163.com


SECURITY_CONFIG_KEY = 'SECURITY'
DEFAULT_SECURITY_JWT_SECRET = 'namekox'
DEFAULT_SECURITY_JWT_MAXAGE = 2 * 60 * 60
DEFAULT_SECURITY_JWT_EXPIRE = 24 * 60 * 60
